graduacao_title = ["Matrícula" , "Graduação - Grade Curricular" , "O que são créditos?" , "O que é Requisito?"]


graduacao_topics = ["Todos os convocados precisam realizar a matrícula virtual para garantir sua vaga na USP.\nA matrícula virtual será realizada no Sistema Júpiter da USP, haverá um tutorial para esclarecer esse processo. Nessa etapa o candidato deve preencher os formulários e enviar os documentos pedidos em forma digital.\n\nNÃO HAVERÁ MATRÍCULA PRESENCIAL." , 
                    "Você pode encontrar toda a grade de disciplinas da Eng. Comp. no sistema Júpiter Web:" , 
                    "Não bixo, a USP não está te dando dinheiro. Créditos são o número de horas-aula (50 minutos) que uma disciplina ocupa por semana. Por exemplo, as aulas de Física I te tomarão 5 horas-aula por semana. Se você consultar o JupiterWeb poderá ver quanto isso resulta em horas totais cumpridas em um semestre. O sistema JupiterWeb é uma ferramenta interessante para ajudar sua organização acadêmica e será apresentada a frente." ,
                    "Como o próprio nome já diz, ele consiste de uma disciplina que deve ter sido cursada anteriormente para que uma outra possa ser. As disciplinas vão formando assim uma hierarquia.\nAntes de cursar uma disciplina é importante verificar quais são os requisitos dela, pois desse jeito dá para se ter uma boa idéia de como as matérias dela vão fluir. Por exemplo, uma disciplina que tenha o requisito SMA0301 (Cálculo I) vai utilizar o conhecimento dessa disciplina em algum momento.\n\nRequisito fraco: Para se cursar Física 2 (2º semestre), por exemplo, é preciso quebrar o requisito fraco em Física 1, o que significa que você deve ter cursado Física 1 e ter tido média igual ou maior que 3,0 e freqüência maior ou superior a 70%.\nRequisito forte: Requer que o aluno tenha sido aprovado nas disciplinas. Felizmente não temos nenhuma disciplina obrigatória que exija requisito forte.\n\nUm lembrete, mais importante que cuidar das notas é cuidar da freqüência. Caso você não complete 70% de presença em uma disciplina, não importa qual seja sua nota, você será reprovado sem quebrar o pré! Por isso tome cuidado e vá às aulas!"]

link_grade_curricular = "https://uspdigital.usp.br/jupiterweb/listarGradeCurricular?codcg=97&codcur=97001&codhab=0&tipo=N"
