nusp_title = ["Número USP" , "E-mail USP" , "JúpiterWeb" , "G-Suite USP"]


nusp_topics = ["O Número USP ou NUSP é sua identificação na USP (como se fosse o RG). Esse número é usado em tudo e em algumas semanas você vai decorar. Com o Número USP você deve criar sua SENHA ÚNICA.", 
               "O principal canal de comunicação entre aluno e USP, Professores e Graduação. Você recebe todas as informações no e-mail USP. É SUPER indicado adicionar sua conta no celular para ver todos os dias o e-mail. Recebemos muitas coisas todos os dias, muito mesmo (até nota de falecimento), estão para não perder e-mails importantes, tenha habito de visualiza-lo todos os dias. O e-mail USP tem o mecanismos iguais ao Gmail (G-Suite USP). É fácil configurar no seu celular.\n\nCuidado ao criar o e-mail USP. Depois de criado, não é possível alterar o nome e esse e-mail será usado em documentos oficiais da USP. NADA de gatinho2000@usp.br! É comum os alunos usarem o nome e um sobrenome. Ex: perryoliveira@usp.br" ,
               "Então bixo, para evitar filas intermináveis e desperdício de papel, a USP criou um sistema para ajudar (e aliviar o serviço de graduação) professores, alunos e departamentos. O nome desse sistema é JúpiterWeb, no caso da graduação (existem outros, mas para você ainda não são relevantes).\nQuando você fez sua matrícula, além do papel que vendia um pedaço da sua alma para a USP, você colocou CPF, RG, quantos rins você ainda tem e outras milhares de informações. Todas elas serão colocadas no, comumente chamado, Júpiter para que você e professores possam ter contato com elas. Você encontrará todo o seu histórico acadêmico, notas, presença, e outras informações importantes sobre seu currículo acadêmico. Também é no Júpiter que você encontra a emissão de documentos, atestado de matrícula, declarações, etc...\nE no Júpiter também que você fará sua matrícula a partir do segundo semestre e também de onde alguns professores tiram informações para criação de sistemas de submissão online.\nDesde já é bom avisar, TODA a USP faz matrícula no mesmo período, no mesmo sistema, então...Não se estresse com a lentidão do sistema nessa época. O JúpiterWeb é bem útil e é bom que você o frequente regularmente. Muitas das inscrições que dependem de rendimento acadêmico vão pedir uma cópia impressa do Júpiter (outras, mais rigorosas pedem um histórico emitido pela Secretaria de Graduação)." , 
               "A USP e a Google firmaram um termo de cooperação que possibilita a alunos, docentes e servidores técnicos e administrativos da Universidade a utilização dos recursos que compõem a ferramenta G Suite for Education. Tais recursos incluem o uso ILIMITADO dos serviços de e-mail, com controle de spam, calendário, contato, comunicação digital, armazenamento e compartilhamento de documentos.\nPara os membros da comunidade universitária, a cooperação possibilita armazenamento ILIMITADO do Google Drive e administração do e-mail USP por mecanismos iguais ao Gmail, customizados para o ambiente da Universidade.\n\nVale lembrar, que mesmo com armazenamento ilimitado NUNCA use para pirataria e arquivos pessoais. G-Suite é para assuntos acadêmicos!" ]


nusp_image_name = [None , None , "logo_jupiterweb.jpg" , "g_suite.png"]